// Generated by CoffeeScript 1.7.1
(function() {
  var UglifyJS;

  UglifyJS = require("uglify-js");

  exports.minifyJS = function(str, options) {
    return UglifyJS.minify(str, {
      fromString: true,
      compress: options
    });
  };

}).call(this);

//# sourceMappingURL=api.map
